baseurl: "https://example.com"
languageCode: "en-us"
title: "Billal BEGUERADJ"
theme: "hugo-tania"
paginate: 6

# disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji:

  # Logo will show before the blog title on site navbar.
  # titleLogo: favicon.ico

  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "Billal BEGUERADJ software, programming, security, startup"
  siteDesc: "Billal BEGUERADJ shoftware development, programming, information security, startup"
  author: "Billal BEGUERADJ"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to: https://dev.to/begueradj
    email:
    facebook:
    github: https://github.com/begueradj
    instagram:
    linkedin:
    medium:
    stack-overflow: https://stackoverflow.com/users/3329664/billal-begueradj
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp:
  
  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP

menu:
  header:
    - name: Articles
      url: "/articles/"
    - name: About
      url: "/about/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
