baseurl = "https://www.begueradj.com/"
DefaultContentLanguage = "en"
title = "Begueradj"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-91013731-1"



[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Software Engineering & Information Security"
  logo = "begueradj.png" # Expecting square dimensions
  favicon = "begueradj.png"
  dateFormat = "January 2, 2006"
  commit = false
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Billal Begueradj"
  github = "begueradj"
  stackoverflow = "users/3329664/billal-begueradj"


[[menu.main]]
    name = "About"
    url = "about/"
    weight = 3

[[menu.main]]
    name = "Categories"
    url = "categories"
    weight = 3

[permalinks]
  post = "/:title"
